### ISSUE TITLE
[Req] Open in OD instead of Libby

### ISSUE THREAD

**Issue by p1nkyy** [Dylancyclone/goodreads-libby-userscript#1]
Hi, is it possible for the script to open the books in each OD site besides going to Libby?
My Libby is maxed out in terms of library cards saved and it makes it glitchy if I want to see the titles in each libraries.
Thank you before.

**Comment by Dylancyclone** [comment]
Hi, sorry for the delay. This has been added and was just released in 1.2.0. Please let me know if everything works for you!
