### ISSUE TITLE
'Save Libraries' Not Showing Up

### ISSUE THREAD

**Issue by mslmn** [Dylancyclone/goodreads-libby-userscript#3]
I've tried the userscript with both Tapermonkey and Violentmonkey, and I cant seem to get it to work. The 'Save Libraries' option just doesn't show up. 

![libby](https://github.com/user-attachments/assets/a90915e2-2032-4bba-854c-777d4bae40ff)

**Comment by Dylancyclone** [comment]
Looks like Libby gave that page a makeover!

Try the latest version and let me know if that fixes it!

**Comment by mslmn** [comment]
Fixed. Thanks!
